CREATE TABLE [dbo].[Tags]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Tags_Id] DEFAULT NEWID(),
    [Name] NVARCHAR(100) NOT NULL,
    [Slug] NVARCHAR(120) NOT NULL,
    [CreatedAt] DATETIME2(3) NOT NULL CONSTRAINT [DF_Tags_CreatedAt] DEFAULT SYSUTCDATETIME(),
    [UpdatedAt] DATETIME2(3) NOT NULL CONSTRAINT [DF_Tags_UpdatedAt] DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Tags_Name] UNIQUE NONCLUSTERED ([Name] ASC),
    CONSTRAINT [UQ_Tags_Slug] UNIQUE NONCLUSTERED ([Slug] ASC)
);
